node {
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/HC.git'
    }

    if (params.PLAN){
        stage('Plan') {
            ansiColor('css') {
                echo "##################"
                echo "# TERRAFORM PLAN #"
                echo "##################"
                
                dir('infra') {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'AWS CREDENTIALS', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'], string(credentialsId: 'TF_VAR_db_password', variable: 'TF_VAR_db_password')]) {
                            sh '''
                                terraform version
                                terraform init
                                terraform plan
                                '''
                    }
                }
            }
        }
    }

    stage('Approval') {
        def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
    }

    stage('Apply') {
        ansiColor('css') {
            echo "###################"
            echo "# TERRAFORM APPLY #"
            echo "###################"
            
            dir('infra') {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'AWS CREDENTIALS', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'], string(credentialsId: 'TF_VAR_db_password', variable: 'TF_VAR_db_password')]) {
                        sh '''
                            terraform apply -input=false
                            '''
                }
            }
        }
    }
}
