node {
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/HC.git'
    }

    stage('Plan') {
        echo "##################"
        echo "# TERRAFORM PLAN #"
        echo "##################"
        
        dir('infra') {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'TF_VAR_secret_key', credentialsId: 'AWS', secretKeyVariable: 'TF_VAR_access_key']]) {
                withCredentials([string(credentialsId: 'TF_VAR_db_password', variable: 'TF_VAR_db_password')]) {
                    ansiColor('xterm') {
                        sh "/usr/bin/terraform version"
                        sh "/usr/bin/terraform init"
                        sh "/usr/bin/terraform plan"
                    }
                }
            }
        }
    }
}