def sitePackageDir = "env/lib/python3.6/site-packages"
def runtimeDir = "python/lib/python3.6/"
node {
    stage('Clean Up'){
        cleanWs()
    }
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/HC.git'
    }

    stage('Dependencies') { 
            echo "################"
            echo "# DEPENDENCIAS #"
            echo "################"
            
            sh "python3 -m venv env"
            sh """. env/bin/activate
            python3 -m pip install -r dependencies/requirements.txt
            deactivate"""
            
        withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1') {
            sh """
            mkdir -p ${runtimeDir}
            cp -r ${sitePackageDir} ${runtimeDir}
            zip -qr9 dependencies.zip ${runtimeDir}
            python3 -m pip install --upgrade awscli
            aws s3 cp dependencies.zip s3://jmpcba-lambda/dependencies.zip
            aws lambda publish-layer-version --layer-name dependencies_layer --description "dependencies_layer"
            --content S3Bucket=jmpcba-lambda,S3Key=dependencies.zip --compatible-runtimes python3.6
            """
        }
    }
}