def sitePackageDir = "env/lib/python3.6/site-packages"
node {
    stage('Clean Up'){
        cleanWs()
    }
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/HC.git'
    }

    stage('Dependencies') { 
            echo "################"
            echo "# DEPENDENCIAS #"
            echo "################"
            sh "python3 -m venv env"
            sh """. env/bin/activate
            python3 -m pip install -r dependencies/requirements.txt
            deactivate"""
            
            dir(sitePackageDir){
                sh """zip -qr9 dependencies.zip .
                aws s3 cp dependencies.zip s3://jmpcba-lambda/dependencies.zip
                """
            }
    }
}