node {
    stage('Clean Up'){
        cleanWs()
    }
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/HC.git'
    }

    stage('Build') { 
        echo "#########################"
        echo "# BUILDING DEPENDENCIES #"
        echo "#########################"
        dir('src') {
            sh "python3 -m pip install -r requirements.txt --target lib --system"
            sh "zip -r9 function.zip ."
        }
    }
    stage('Deploy') {
        echo "####################"
        echo "# UPLOADING TO AWS #"
        echo "####################"
        dir('src') {
            echo "uploading to S3"
            withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1') {
                sh "aws s3 cp function.zip s3://jmpcba-lambda/function.zip"
            }
            
            echo "updating function code"
            withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1') {
                sh "aws lambda update-function-code --function-name HC_data_service --zip-file fileb://function.zip"
            }
        }
    }
}