
def sitePackageDir = "env/lib/python3.6/site-packages"
node {
    stage('Clean Up'){
        cleanWs()
    }
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/HC.git'
    }

    stage('Build') { 
        echo "############"
        echo "# FUNCION #"
        echo "###########"
        dir("src"){
            sh "zip -qr9 function.zip ."
        }
    }

    stage('Deploy') {
        echo "####################"
        echo "# UPLOADING TO AWS #"
        echo "####################"  
            withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1') {
            sh """. env/bin/activate
            python3 -m pip install --upgrade awscli
            which aws
            aws s3 cp function.zip s3://jmpcba-lambda/function.zip
            aws lambda update-function-code --function-name HC_prestador_service --s3-bucket jmpcba-lambda --s3-key function.zip
            aws lambda update-function-code --function-name HC_paciente_service --s3-bucket jmpcba-lambda --s3-key function.zip
            deactivate"""
        }
    }
}