node {
    stage('Clean Up'){
        cleanWs()
    }
    stage('Clone'){
        git credentialsId: 'GIT', url: 'https://github.com/jmpcba/HC.git'
    }

    stage('Build') { 
        echo "#########################"
        echo "# BUILDING DEPENDENCIES #"
        echo "#########################"
        sh "python3 -m virtualenv env"
        sh ". env/bin/activate"
        sh "cp src/* env/Lib/site-packages"
        sh "python3 -m pip install -r requirements.txt --target lib --system"
        sh "zip -r9 function.zip env/Lib/site-packages"
    }

    stage('Deploy') {
        echo "####################"
        echo "# UPLOADING TO AWS #"
        echo "####################"            
        withAWS(credentials: 'AWS CREDENTIALS', region: 'us-east-1') {
            sh "aws s3 cp function.zip s3://jmpcba-lambda/function.zip"
            sh "aws lambda update-function-code --function-name HC_data_service --zip-file fileb://function.zip"
        }
    }
}